apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john-developer
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbTlvYmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU0xaGNpU1k3VGg2OE5hRnVYQnR6TlpiTWhRUXJkUVMvMUd4d2tuaDc3clRXRDA1CnR2Mlp2MUtCNEVISG92WG1GUFYzd0I1V2dTNld1Y2F3b29uUENHbGwvQXFzb21SMEFicVhUZEZqejdqVEtMcmwKYUtrRnUyUHlhTDloUUtVWC8yME5sVUNpN1NiY3FJTHZaY0tVUWplekNWOUQ3QzJDUURXR1hBdU9mWWVjamxveQp5Y0VmTDdGVC9aQ0tBL1ZZVU9xczFJY1U3R0pvS3hCOW10bThzT1F1RXk0N2hDNEtvSDBONzdBRXZDMTU0SDJRClBaTHZCMXg5MHliTXc4QWdRS01XR1E0QnVVTlVWQUs0bjRpRFgvSmIxTTRaQUowVjlENVYvNnQ4QXhIVm9IVGkKNzlvanNYbFoxLys5dk45RjlONWpFVmZRVXFnaFZxZ1ZxUzBMM0FVQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQ0VTQ3lJZjZFVnprYlpVNHc2YnE4ZWtzNC81U3drOWhPZHBwUUl0SHd4OUgweFZoa3BVYWZuCllmT2FkUWZZZndOUGoyNXB5YS9ldFhZTW56Y2lQcnNkajJJckFxQ3Z6djR0Q3JUM1Y0WHBhK3dkVFBvTWU2blQKUlp2MFZPd2Y0ZFlYeDhKWkE4bVhiTnlDTU5IOXRCRkZvNHVVWDBWUmxnR245N0VuWGdoL3NoeFpNUmFyUXdKawpXa1dpamxtaWlSd1RJV3dTeXRIcHdqY3RpL25QYUltZ25IUU1Tell3TEZXYXhQQys5L2lNbVZwdFo5bURqOFF2ClFaa3Evdis3Ym4xU1dFaFkzcmZRRmFubHEzZ0R2QVN4am1OMkQ1d3JNRUgyN1dDZnNLdW5TelZBSmhjYWQ2bFAKbjVhSGh1czM0Z3plTFdZaTZMTk5VQU84dXdHYjU3LzUKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==

# The request string should be the base64 version of the .csr file