apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  lables:
    name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: app-secret

# 3 methods for using Secrets
# 1. Read all env variables form a Secret.  This is the example above.
# 2. Read single env variable from a Secret.
# 
# ```yaml
# env:
#   - name: DB_Password
#     valueFrom:
#       secretKeyRef:
#         name: app-secret
#         key: DB_Password
# ```
# 
# 3. Read from a Volume
# 
# ```yaml
# volumes
#   - name: app-secret-volume
#     configMap:
#       name: app-secret
# ```
# 
# If using a volume, each variable should be stored as it's own file and the content of the file is the variable value.
# 
# ```bash
# > ls /opt/app-secret-volumes
# DB_Host      DB_Password      DB_User
# 
# > cat /opt/app-secret-volumes/DB_Password
# paswrd
# ```
.